### ISSUE TITLE
B450 Tomahawk does work with msirgb

### ISSUE THREAD

**Issue by sirBBBmlg** [ixjf/MSIRGB#67] opened 2019-11-21 20:41 UTC
Title says everthing ( U safed my ass with that programmty)

**Comment by sirBBBmlg** [comment] 2019-11-26 16:12
it isnt loading the scripts right after a few start ups

**Comment by ixjf** [comment] 2019-12-02 15:01
I think this is a known bug. Does this:

https://github.com/ixjf/MSIRGB/issues/43#issuecomment-525195336

describe more or less your problem?

**Comment by ixjf** [comment] 2020-09-06 11:36
Closing as it is a duplicate of #43. Please refer to that issue for info on the status of the fix.

**Closed by ixjf** 2020-09-06 11:36 UTC
Labels: bug, duplicate
