### ISSUE TITLE
MSI Gaming Plus Max also has the reversed color issue 

### ISSUE THREAD

**Issue by psisquared2** [ixjf/MSIRGB#123] opened 2020-06-17 10:54 UTC
As the title says, the MSI Gaming Plus MAX is also affected by #106. This is in contrast to the non-MAX version which someone else reported to work without issue.

Interestingly, the MSI Mystic Light tool also applies reversed colors even after I close MSIRGB. It is only fixed after a reboot.

Please let me know if I can help by providing further information to add this mainboard to the supported list.

**Comment by ixjf** [comment] 2020-09-05 17:23
MSIRGB v2.3.0 fixes the reversed colour issue. Please try the new version.

**Comment by ixjf** [comment] 2020-09-06 11:32
Closing as it is a duplicate of #139.

**Closed by ixjf** 2020-09-06 11:32 UTC
Labels: bug, duplicate

**Comment by psisquared2** [comment] 2020-09-09 10:23
I can confirm that the B450 MSI Gaming Plus MAX now works as intended. Thank you!

**Comment by ixjf** [comment] 2020-09-09 13:06
Great, thanks for the feedback!
