### ISSUE TITLE
MSIRGB not working

### ISSUE THREAD

**Issue by Arsenic333** [ixjf/MSIRGB#147] opened 2020-09-13 11:40 UTC
i followed all the steps but whenever i tyr to launch MSIRGB.exe it says fialed to load driver
![MSIRGB not working](https://user-images.githubusercontent.com/71215557/93017147-4e089c80-f5be-11ea-9254-4fc67b514835.PNG)
can anyone help me out

**Comment by ixjf** [comment] 2020-09-13 14:00
Do you have Riot Vanguard installed?

**Comment by Arsenic333** [comment] 2020-09-13 14:12
yes

**Comment by Arsenic333** [comment] 2020-09-13 14:12
should i uninstall it
or disable it

**Comment by Arsenic333** [comment] 2020-09-13 14:13
ok it works now thx

**Comment by Arsenic333** [comment] 2020-09-13 14:33
but when i restart my pc it doesnt work
it will only work when i manually disable vanguard first everytime i turn on my pc, Not when vanguard is disabled from start up

**Comment by ixjf** [comment] 2020-09-13 16:09
Unfortunately, Vanguard does not allow MSIRGB to run as it thinks it might be used as a cheat. This is a known issue. In the meantime, you should either stop using Vanguard altogether or disable it when using MSIRGB.

**Comment by ixjf** [comment] 2020-09-13 16:22
I'm closing this as it is a duplicate of #115. Please refer to that issue for status on the fix.

**Closed by ixjf** 2020-09-13 16:22 UTC
Labels: bug, duplicate
