### ISSUE TITLE
MSI Mortat TITANUM - reversed colors

### ISSUE THREAD

**Issue by majsterkovic** [ixjf/MSIRGB#87] opened 2020-03-17 13:16 UTC
It is not working properly for my motherboard. The colors are the opposite.

**Comment by ixjf** [comment] 2020-09-05 16:50
Which motherboard exactly?

**Comment by ixjf** [comment] 2020-09-05 17:25
MSIRGB v2.3.0 fixes the reversed colour issue. Please try the new version.

**Comment by ixjf** [comment] 2020-09-06 11:33
Closing as it is a duplicate of #139.

**Closed by ixjf** 2020-09-06 11:33 UTC
Labels: bug, duplicate
