### ISSUE TITLE
Music Sync

### ISSUE THREAD

**Issue by prameenson** [ixjf/MSIRGB#127] opened 2020-06-27 16:02 UTC
The application works flawlessly, the only thing I miss is the music sync.
Can someone please help me with a script for the same?
Thanks in advance :)

**Comment by FiddleStickers** [comment] 2020-07-29 21:26
+1

also I wish to know if this supports MSI graphics cards, as I want to get rid of Dragon Center =)

**Comment by ixjf** [comment] 2020-09-06 11:41
Closing as it is a duplicate of #119. Please refer to that issue for status information.

**Closed by ixjf** 2020-09-06 11:41 UTC
Labels: enhancement
