### ISSUE TITLE
B450 Tomahawk max reversed colors

### ISSUE THREAD

**Issue by nagynorbert97** [ixjf/MSIRGB#85] opened 2020-02-26 16:13 UTC
The whole thing works fantastic when i run the Hue script and that was the reason why i donwloaded it, but all the manually set colors are reverse. Is there any easy fix to do it myself?

**Comment by ixjf** [comment] 2020-03-02 11:36
Currently, the only way is to fork the branch, apply the pull request #48, and build MSIRGB yourself (or at least MSIRGB.DLL, the other binaries don't need to be rebuilt).

**Comment by ixjf** [comment] 2020-09-05 17:24
MSIRGB v2.3.0 fixes the reversed colour issue. Please try the new version.

**Comment by ixjf** [comment] 2020-09-06 11:33
Closing as it is a duplicate of #139.

**Closed by ixjf** 2020-09-06 11:33 UTC
Labels: bug, duplicate
