### ISSUE TITLE
Works on MSI B450 Tomahawk but with Inverted Colors

### ISSUE THREAD

**Issue by cm959** [ixjf/MSIRGB#106] opened 2020-05-05 22:10 UTC
0 is f and f is 0 - it can still be used, but the colors onscreen are wrong, the "breathing" mode starts bright and switches colors at full brightness, and blinking modes blink off when they should be on (less noticeable).

**Comment by AnnoyingBarnacle422** [comment] 2020-05-13 05:33
I have this issue as well.

**Comment by ixjf** [comment] 2020-05-15 11:19
This is a known issue that I haven't been able to fix because I don't have access to my desktop computer.

**Comment by ixjf** [comment] 2020-09-05 17:24
MSIRGB v2.3.0 fixes the reversed colour issue. Please try the new version.

**Comment by ixjf** [comment] 2020-09-06 11:32
Closing as it is a duplicate of #139.

**Closed by ixjf** 2020-09-06 11:32 UTC
Labels: bug, duplicate
