### ISSUE TITLE
B450 GAMING PLUS MAX not working correctly 

### ISSUE THREAD

**Issue by Hatry1337** [ixjf/MSIRGB#134] opened 2020-08-07 17:33 UTC
I see only randomly blinking colors. Also colors are reversed.

**Comment by ixjf** [comment] 2020-09-05 17:22
MSIRGB v2.3.0 fixes the reversed colour issue. Please try the new version.

**Comment by ixjf** [comment] 2020-09-06 11:32
Closing as it is a duplicate of #139.

**Closed by ixjf** 2020-09-06 11:32 UTC
Labels: bug, duplicate
